Create notification service
ita-social-projects/SoftServeCar-Back-End pull request #115
Opened 2020-12-14 21:38 UTC by bogdangavrylyak

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2020-12-16 12:38 UTC, BorysMalynovskyi reviewed
Unrelated files included

2021-01-18 12:51 UTC, AntonukOM requested changes

2021-01-18 12:51 UTC, AntonukOM commented on CarBackEnd/Car.BLL/Services/Implementation/GoogleDriveService.cs
> +            return (await service.Files.List().ExecuteAsync()).Files;
please revert extra space

2021-01-18 12:51 UTC, AntonukOM commented on CarBackEnd/Car.BLL/Services/Implementation/SmtpClientService.cs
> +                    client.AuthenticationMechanisms.Remove("XOAUTH2");
the string value is hardcoded, move to const

2021-01-18 12:51 UTC, AntonukOM commented on CarBackEnd/Car.BLL/Services/Implementation/EmailSenderService.cs
> +               "/Views/Emails/CancelJourney/CancelJourney.cshtml",
move this path to const

2021-01-18 12:51 UTC, AntonukOM commented on CarBackEnd/Car.BLL/Services/Implementation/EmailSenderService.cs
> +                lr.ContentId = "imgpath";
hardcode

2021-01-18 12:51 UTC, AntonukOM commented on CarBackEnd/Car.BLL/Services/Implementation/EmailSenderService.cs
> +                message.Subject = $"Your journey has been cancelled";
suggest move messages to the const class, ex EmailMessageConstants

2021-01-18 12:51 UTC, AntonukOM commented on CarBackEnd/Car.BLL/Services/Implementation/EmailSenderService.cs
> +                LinkedResource lr = new LinkedResource(message.Attachments.OpenReadStream());
please use the full names of variables: linkedResource

2021-01-18 12:51 UTC, AntonukOM commented on CarBackEnd/CarBackEnd/CarBackEnd.csproj
> +    <DocumentationFile>F:\SoftServeCarProject\BackEnd7\Car-Back-End\CarBackEnd\CarBackEnd\CarBackEnd.xml</DocumentationFile>
this config is hardcoded

2021-01-18 12:51 UTC, AntonukOM commented on CarBackEnd/CarBackEnd/CarBackEnd.csproj
> +  <ItemGroup>
do we need to add this folder?

2021-01-18 12:51 UTC, AntonukOM commented on CarBackEnd/CarBackEnd/Controllers/UserController.cs
> +            return Ok(await imageService.UploadImage(userId, userFile.image));
please revert spaces

2021-01-18 12:51 UTC, AntonukOM commented on CarBackEnd/Car.BLL/Services/Interfaces/IEmailSenderService.cs
> +        Task CancelJourneyAsync(Message mailingMessage);
please add a unit test coverage

2021-01-18 12:51 UTC, AntonukOM commented on CarBackEnd/Car.BLL/Services/Interfaces/ISmptClient.cs
> +        Task SendAsync(MimeMessage mailMessage, EmailConfiguration emailConfiguration);
please add a unit test coverage

2021-02-11 09:03 UTC, closed without merging