Closed #146 - Write tests
ita-social-projects/SoftServeCar-Back-End pull request #180
Opened 2021-01-20 18:53 UTC by strelovidniy

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-01-22 08:48 UTC, AntonukOM requested changes

2021-01-22 08:48 UTC, AntonukOM commented on Car.Backend/Car.UnitTests/Controllers/UserControllerTest.cs
> +        public User GetTestUser() =>
please remove this method and use Fixture to create a model

2021-01-22 08:48 UTC, AntonukOM commented on Car.Backend/Car.UnitTests/Controllers/UserControllerTest.cs
>              using (new AssertionScope())
we don't need multiple assertions
check these lines
_((result as OkObjectResult)?.Value as User)?.Id.Should().Be(user.Id);
((result as OkObjectResult)?.Value as User)?.Name.Should().Be(user.Name);_
would be enough

2021-01-22 08:48 UTC, AntonukOM commented on Car.Backend/Car.UnitTests/Controllers/UserControllerTest.cs
>              using (new AssertionScope())
omit this usage

2021-01-27 13:41 UTC, IhorSolovii approved these changes

2021-01-27 13:50 UTC, anastasiiakolomyi approved these changes
good

2021-01-27 13:51 UTC, merged