added filtering journeys controller action with appropriate service m…
ita-social-projects/SoftServeCar-Back-End pull request #409
Opened 2021-05-06 21:04 UTC by roman-pankiv

…ethods

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-05-06 21:07 UTC, vovazavislyak approved these changes

2021-05-06 22:03 UTC, AntonukOM commented on Car.Backend/Car.UnitTests/Controllers/JourneyControllerTest.cs
> +            using (new AssertionScope())
I think we can remove AssertionScope

2021-05-06 22:07 UTC, AntonukOM requested changes

2021-05-06 22:07 UTC, AntonukOM commented on Car.Backend/Car.UnitTests/Services/JourneyServiceTest.cs
> +            result.Should().NotBeNull();
you should check that result should be equal to expected journeys

2021-05-06 22:07 UTC, AntonukOM commented on Car.Backend/Car.UnitTests/Controllers/JourneyControllerTest.cs
> +                (result as OkObjectResult)?.Value.Should().NotBeNull();
please verify that the result value is equal to the expectedResult

2021-05-07 05:38 UTC, roman-pankiv commented on Car.Backend/Car.UnitTests/Controllers/JourneyControllerTest.cs
> +            using (new AssertionScope())
Done

2021-05-07 05:38 UTC, roman-pankiv commented on Car.Backend/Car.UnitTests/Services/JourneyServiceTest.cs
> +            result.Should().NotBeNull();
Done

2021-05-07 05:38 UTC, roman-pankiv commented on Car.Backend/Car.UnitTests/Controllers/JourneyControllerTest.cs
> +                (result as OkObjectResult)?.Value.Should().NotBeNull();
Done

2021-05-07 08:34 UTC, AntonukOM approved these changes

2021-05-07 08:34 UTC, AntonukOM approved these changes

2021-05-08 11:03 UTC, bohatyrov approved these changes

2021-05-08 11:09 UTC, merged